apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: github-pages
  namespace: external-dns
spec:
  endpoints:
    - dnsName: andresfelipemendez.com
      recordTTL: 300
      recordType: A
      targets:
        - 185.199.108.153
        - 185.199.109.153
        - 185.199.110.153
        - 185.199.111.153
