apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: website=ghcr.io/andresfelipemendez/andresfelipemendez.github.io:latest
    argocd-image-updater.argoproj.io/website.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andresfelipemendez/cluster-config.git
    targetRevision: HEAD
    path: apps/website
  destination:
    server: https://kubernetes.default.svc
    namespace: website
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
